include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_renaming_method_parameters: false
    prefer_relative_imports: true
    avoid_redundant_argument_values: true
    type_annotate_public_apis: true
    parameter_assignments: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    use_super_parameters: true
    unused_element: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    body_might_complete_normally_nullable: ignore
    unused_element: ignore
