name: adb_ui
description: Run adb commands with ease from a simple UI
publish_to: none
version: 0.0.13

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  dynamic_color: ^1.5.4
  intl: ^0.17.0
  animations: ^2.0.7
  logging: ^1.1.0
  validators: ^3.0.0
  google_fonts: ^3.0.1
  freezed_annotation: ^2.2.0
  lottie: ^1.4.3
  network_info_plus: ^2.3.2
  file_picker: ^5.2.2
  desktop_drop: ^0.3.3
  cross_file: ^0.3.3+2
  async: ^2.9.0
  riverpod_annotation: ^1.0.4
  sliver_tools: ^0.2.8
  window_manager: ^0.2.7
  uuid: ^3.0.6
  device_info_plus: ^8.0.0
  archive: ^3.3.2
  path_provider: ^2.0.11
  path: ^1.8.2
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  url_launcher: ^6.1.6
  collection: ^1.16.0
  package_info_plus: ^3.0.1
  github: ^9.5.0
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/
