name: Build Mac OS
"on":
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
jobs:
  build:
    runs-on: macos-latest
    env:
      RELEASE_PATH: build/macos/Build/Products/Release
      APPNAME: "adb-ui"
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.4.0

      - name: Install node
        uses: actions/setup-node@master

      - name: Instal appdmg
        run: npm install -g appdmg

      - name: Build Mac app
        run: flutter build macos --release

      - name: Make .dmg file
        run: |
          appdmg Installers/dmg_creator/config.json ${{ github.workspace }}/${{env.RELEASE_PATH}}/${{env.APPNAME}}-setup-macos-dmg
      # - name: Run Installers/installer.iss Inno script
      #   run: |
      #     "%programfiles(x86)%\Inno Setup 6\iscc.exe" /dversion=${{env.VERSION}} "Installers/installer.iss"
      #   shell: cmd

      - name: Upload Macos dmg
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.APPNAME}}-setup-macos-dmg
          path: ${{env.RELEASE_PATH}}//${{env.RELEASE_PATH}}/${{env.APPNAME}}-setup-macos-dmg
