name: Build Linux
"on":
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
