name: Build Mac OS
"on":
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        default: "0.0.0"
        type: string
jobs:
  build:
    runs-on: macos-latest
    env:
      RELEASE_PATH: build/macos/Build/Products/Release
      APPNAME: "adb-ui"
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
